### ISSUE TITLE
Make sure the Record a Measurement button always works

### ISSUE THREAD

**Issue by AMelhede** [curedao/curedao-monorepo#47]
When I try to record a measurement it some goes to the study page as shown below:
![image](https://user-images.githubusercontent.com/95473109/227219891-477bdb1c-2b37-415a-851d-b2a98d9e9881.png)

![image](https://user-images.githubusercontent.com/95473109/227219841-84f82ef2-0888-4d32-89ba-a882061261e3.png)

Study page:
https://app.curedao.org/app/public/#/app/study

Record a measurement page:
https://app.curedao.org/app/public/#/app/measurement-add-search

**Comment by mikepsinn** [comment]
Are you sure the measurement doesn't save?  I'm pretty sure it's being saved.  I think the issue is that after saving, it just checks the history and redirects you back to the last non-variable search page, apparently a study for you.  Does that seem plausible?

What is a preferred or expected behavior after saving the measurement?

**Comment by AMelhede** [comment]
So, it actually doesn't direct me to the study page after inputting a new measurement.

The issue is regards when I press "Record a measurement" it occasionally goes to the study section rather than to the actual place to record a new measurement.
Does that make sense?

**Comment by mikepsinn** [comment]
Thanks, @AMelhede !  I can't reproduce this, so I guess it's fixed.  Please let me know if I'm mistaken. :)
